name: Sync VK Transactions

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Скачивание репозитория
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Установка библиотек
        run: pip install requests

      - name: Запуск парсера ВК
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
        run: python sync.py

      - name: Сохранение новых чеков на сайт
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --staged --quiet; then
            echo "Новых данных нет"
          else
            git commit -m "Авто-обновление чеков из ВК"
            git push
          fi
